// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/bridge.proto

package bridgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhatsAppBridge_Connect_FullMethodName                      = "/bridge.WhatsAppBridge/Connect"
	WhatsAppBridge_Disconnect_FullMethodName                   = "/bridge.WhatsAppBridge/Disconnect"
	WhatsAppBridge_GetQRCode_FullMethodName                    = "/bridge.WhatsAppBridge/GetQRCode"
	WhatsAppBridge_GetLinkCode_FullMethodName                  = "/bridge.WhatsAppBridge/GetLinkCode"
	WhatsAppBridge_SendMessage_FullMethodName                  = "/bridge.WhatsAppBridge/SendMessage"
	WhatsAppBridge_SendMedia_FullMethodName                    = "/bridge.WhatsAppBridge/SendMedia"
	WhatsAppBridge_SendLink_FullMethodName                     = "/bridge.WhatsAppBridge/SendLink"
	WhatsAppBridge_SendContact_FullMethodName                  = "/bridge.WhatsAppBridge/SendContact"
	WhatsAppBridge_GetMessageStatus_FullMethodName             = "/bridge.WhatsAppBridge/GetMessageStatus"
	WhatsAppBridge_CreateNewsletter_FullMethodName             = "/bridge.WhatsAppBridge/CreateNewsletter"
	WhatsAppBridge_FollowNewsletter_FullMethodName             = "/bridge.WhatsAppBridge/FollowNewsletter"
	WhatsAppBridge_GetNewsletters_FullMethodName               = "/bridge.WhatsAppBridge/GetNewsletters"
	WhatsAppBridge_SendNewsletterPoll_FullMethodName           = "/bridge.WhatsAppBridge/SendNewsletterPoll"
	WhatsAppBridge_GetContacts_FullMethodName                  = "/bridge.WhatsAppBridge/GetContacts"
	WhatsAppBridge_CheckNumber_FullMethodName                  = "/bridge.WhatsAppBridge/CheckNumber"
	WhatsAppBridge_AddContact_FullMethodName                   = "/bridge.WhatsAppBridge/AddContact"
	WhatsAppBridge_GetContactDetail_FullMethodName             = "/bridge.WhatsAppBridge/GetContactDetail"
	WhatsAppBridge_SetProfilePicture_FullMethodName            = "/bridge.WhatsAppBridge/SetProfilePicture"
	WhatsAppBridge_SetStatus_FullMethodName                    = "/bridge.WhatsAppBridge/SetStatus"
	WhatsAppBridge_SetDisplayName_FullMethodName               = "/bridge.WhatsAppBridge/SetDisplayName"
	WhatsAppBridge_GetGroups_FullMethodName                    = "/bridge.WhatsAppBridge/GetGroups"
	WhatsAppBridge_GetGroupMembers_FullMethodName              = "/bridge.WhatsAppBridge/GetGroupMembers"
	WhatsAppBridge_CreateGroup_FullMethodName                  = "/bridge.WhatsAppBridge/CreateGroup"
	WhatsAppBridge_UpdateGroup_FullMethodName                  = "/bridge.WhatsAppBridge/UpdateGroup"
	WhatsAppBridge_AddGroupMembers_FullMethodName              = "/bridge.WhatsAppBridge/AddGroupMembers"
	WhatsAppBridge_RemoveGroupMembers_FullMethodName           = "/bridge.WhatsAppBridge/RemoveGroupMembers"
	WhatsAppBridge_PromoteGroupMembers_FullMethodName          = "/bridge.WhatsAppBridge/PromoteGroupMembers"
	WhatsAppBridge_DemoteGroupMembers_FullMethodName           = "/bridge.WhatsAppBridge/DemoteGroupMembers"
	WhatsAppBridge_LeaveGroup_FullMethodName                   = "/bridge.WhatsAppBridge/LeaveGroup"
	WhatsAppBridge_DeleteMessage_FullMethodName                = "/bridge.WhatsAppBridge/DeleteMessage"
	WhatsAppBridge_SetGroupAdminsOnly_FullMethodName           = "/bridge.WhatsAppBridge/SetGroupAdminsOnly"
	WhatsAppBridge_SetGroupInfoAdminsOnly_FullMethodName       = "/bridge.WhatsAppBridge/SetGroupInfoAdminsOnly"
	WhatsAppBridge_SetGroupAddMembersAdminsOnly_FullMethodName = "/bridge.WhatsAppBridge/SetGroupAddMembersAdminsOnly"
	WhatsAppBridge_ReactToMessage_FullMethodName               = "/bridge.WhatsAppBridge/ReactToMessage"
	WhatsAppBridge_GetMessageReactions_FullMethodName          = "/bridge.WhatsAppBridge/GetMessageReactions"
	WhatsAppBridge_SendStatus_FullMethodName                   = "/bridge.WhatsAppBridge/SendStatus"
	WhatsAppBridge_CommentStatus_FullMethodName                = "/bridge.WhatsAppBridge/CommentStatus"
	WhatsAppBridge_LikeStatus_FullMethodName                   = "/bridge.WhatsAppBridge/LikeStatus"
	WhatsAppBridge_GetStatusViewers_FullMethodName             = "/bridge.WhatsAppBridge/GetStatusViewers"
	WhatsAppBridge_JoinGroupByLink_FullMethodName              = "/bridge.WhatsAppBridge/JoinGroupByLink"
	WhatsAppBridge_CloseAllTabs_FullMethodName                 = "/bridge.WhatsAppBridge/CloseAllTabs"
	WhatsAppBridge_GetAccountStatus_FullMethodName             = "/bridge.WhatsAppBridge/GetAccountStatus"
	WhatsAppBridge_GetConnectionState_FullMethodName           = "/bridge.WhatsAppBridge/GetConnectionState"
	WhatsAppBridge_GetAccountStats_FullMethodName              = "/bridge.WhatsAppBridge/GetAccountStats"
	WhatsAppBridge_GetBridgeStats_FullMethodName               = "/bridge.WhatsAppBridge/GetBridgeStats"
	WhatsAppBridge_GetWebServerStats_FullMethodName            = "/bridge.WhatsAppBridge/GetWebServerStats"
	WhatsAppBridge_BatchGetWebServerStats_FullMethodName       = "/bridge.WhatsAppBridge/BatchGetWebServerStats"
)

// WhatsAppBridgeClient is the client API for WhatsAppBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WhatsAppBridgeClient interface {
	// Connect account (restore from saved session)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Disconnect account
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	// Get QR code (streaming, QR refreshes)
	GetQRCode(ctx context.Context, in *QRCodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QRCodeResponse], error)
	// Get link/pairing code (one-time)
	GetLinkCode(ctx context.Context, in *LinkCodeRequest, opts ...grpc.CallOption) (*LinkCodeResponse, error)
	// Send text message
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// Send media message (image/video/document)
	SendMedia(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SendMediaResponse, error)
	// Send hyperlink message
	SendLink(ctx context.Context, in *SendLinkRequest, opts ...grpc.CallOption) (*SendLinkResponse, error)
	// Send contact card (vCard)
	SendContact(ctx context.Context, in *SendContactRequest, opts ...grpc.CallOption) (*SendContactResponse, error)
	// Get message status
	GetMessageStatus(ctx context.Context, in *MessageStatusRequest, opts ...grpc.CallOption) (*MessageStatusResponse, error)
	// Create a WhatsApp channel/newsletter
	CreateNewsletter(ctx context.Context, in *CreateNewsletterRequest, opts ...grpc.CallOption) (*CreateNewsletterResponse, error)
	// Follow a WhatsApp channel/newsletter
	FollowNewsletter(ctx context.Context, in *FollowNewsletterRequest, opts ...grpc.CallOption) (*FollowNewsletterResponse, error)
	// Get subscribed WhatsApp channels/newsletters
	GetNewsletters(ctx context.Context, in *GetNewslettersRequest, opts ...grpc.CallOption) (*GetNewslettersResponse, error)
	// Send a poll to a WhatsApp channel/newsletter
	SendNewsletterPoll(ctx context.Context, in *SendNewsletterPollRequest, opts ...grpc.CallOption) (*SendNewsletterPollResponse, error)
	// Get contacts list
	GetContacts(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*GetContactsResponse, error)
	// Check if numbers are registered on WhatsApp
	CheckNumber(ctx context.Context, in *CheckNumberRequest, opts ...grpc.CallOption) (*CheckNumberResponse, error)
	// Add contact to address book
	AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error)
	// Get detailed contact information
	GetContactDetail(ctx context.Context, in *GetContactDetailRequest, opts ...grpc.CallOption) (*GetContactDetailResponse, error)
	// Set profile picture
	SetProfilePicture(ctx context.Context, in *SetProfilePictureRequest, opts ...grpc.CallOption) (*SetProfilePictureResponse, error)
	// Set profile status text
	SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*SetStatusResponse, error)
	// Set display name
	SetDisplayName(ctx context.Context, in *SetDisplayNameRequest, opts ...grpc.CallOption) (*SetDisplayNameResponse, error)
	// Get groups list
	GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsResponse, error)
	// Get group members
	GetGroupMembers(ctx context.Context, in *GetGroupMembersRequest, opts ...grpc.CallOption) (*GetGroupMembersResponse, error)
	// Create group
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	// Update group info (name/description)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error)
	// Add members to group
	AddGroupMembers(ctx context.Context, in *AddGroupMembersRequest, opts ...grpc.CallOption) (*AddGroupMembersResponse, error)
	// Remove members from group
	RemoveGroupMembers(ctx context.Context, in *RemoveGroupMembersRequest, opts ...grpc.CallOption) (*RemoveGroupMembersResponse, error)
	// Promote members to admin
	PromoteGroupMembers(ctx context.Context, in *PromoteGroupMembersRequest, opts ...grpc.CallOption) (*PromoteGroupMembersResponse, error)
	// Demote admins to regular members
	DemoteGroupMembers(ctx context.Context, in *DemoteGroupMembersRequest, opts ...grpc.CallOption) (*DemoteGroupMembersResponse, error)
	// Leave group
	LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error)
	// Delete a message for everyone
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
	// Toggle admins-only messaging
	SetGroupAdminsOnly(ctx context.Context, in *SetGroupAdminsOnlyRequest, opts ...grpc.CallOption) (*SetGroupAdminsOnlyResponse, error)
	// Toggle admins-only group info edit
	SetGroupInfoAdminsOnly(ctx context.Context, in *SetGroupInfoAdminsOnlyRequest, opts ...grpc.CallOption) (*SetGroupInfoAdminsOnlyResponse, error)
	// Toggle admins-only add members
	SetGroupAddMembersAdminsOnly(ctx context.Context, in *SetGroupAddMembersAdminsOnlyRequest, opts ...grpc.CallOption) (*SetGroupAddMembersAdminsOnlyResponse, error)
	// React to a message (emoji reaction)
	ReactToMessage(ctx context.Context, in *ReactToMessageRequest, opts ...grpc.CallOption) (*ReactToMessageResponse, error)
	// Get reactions on a message
	GetMessageReactions(ctx context.Context, in *GetMessageReactionsRequest, opts ...grpc.CallOption) (*GetMessageReactionsResponse, error)
	// Post a status/story
	SendStatus(ctx context.Context, in *SendStatusRequest, opts ...grpc.CallOption) (*SendStatusResponse, error)
	// Comment on a status
	CommentStatus(ctx context.Context, in *CommentStatusRequest, opts ...grpc.CallOption) (*CommentStatusResponse, error)
	// Like/react to a status
	LikeStatus(ctx context.Context, in *LikeStatusRequest, opts ...grpc.CallOption) (*LikeStatusResponse, error)
	// Get status viewers (who viewed a status post)
	GetStatusViewers(ctx context.Context, in *GetStatusViewersRequest, opts ...grpc.CallOption) (*GetStatusViewersResponse, error)
	// Join group via invite link
	JoinGroupByLink(ctx context.Context, in *JoinGroupByLinkRequest, opts ...grpc.CallOption) (*JoinGroupByLinkResponse, error)
	// Close all browser tabs (cleanup)
	CloseAllTabs(ctx context.Context, in *CloseAllTabsRequest, opts ...grpc.CallOption) (*CloseAllTabsResponse, error)
	// Get account status
	GetAccountStatus(ctx context.Context, in *AccountStatusRequest, opts ...grpc.CallOption) (*AccountStatusResponse, error)
	// Get connection state
	GetConnectionState(ctx context.Context, in *ConnectionStateRequest, opts ...grpc.CallOption) (*ConnectionStateResponse, error)
	// Get account online statistics
	GetAccountStats(ctx context.Context, in *GetAccountStatsRequest, opts ...grpc.CallOption) (*GetAccountStatsResponse, error)
	// Get bridge-wide stats: worker/environment counts and per-worker detail
	GetBridgeStats(ctx context.Context, in *GetBridgeStatsRequest, opts ...grpc.CallOption) (*GetBridgeStatsResponse, error)
	// Get a single web server's current window usage stats
	GetWebServerStats(ctx context.Context, in *GetWebServerStatsRequest, opts ...grpc.CallOption) (*WebServerStats, error)
	// Batch get current window usage stats for multiple web servers
	BatchGetWebServerStats(ctx context.Context, in *BatchGetWebServerStatsRequest, opts ...grpc.CallOption) (*BatchGetWebServerStatsResponse, error)
}

type whatsAppBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewWhatsAppBridgeClient(cc grpc.ClientConnInterface) WhatsAppBridgeClient {
	return &whatsAppBridgeClient{cc}
}

func (c *whatsAppBridgeClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetQRCode(ctx context.Context, in *QRCodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QRCodeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WhatsAppBridge_ServiceDesc.Streams[0], WhatsAppBridge_GetQRCode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QRCodeRequest, QRCodeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhatsAppBridge_GetQRCodeClient = grpc.ServerStreamingClient[QRCodeResponse]

func (c *whatsAppBridgeClient) GetLinkCode(ctx context.Context, in *LinkCodeRequest, opts ...grpc.CallOption) (*LinkCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkCodeResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetLinkCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SendMedia(ctx context.Context, in *SendMediaRequest, opts ...grpc.CallOption) (*SendMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMediaResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SendMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SendLink(ctx context.Context, in *SendLinkRequest, opts ...grpc.CallOption) (*SendLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendLinkResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SendLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SendContact(ctx context.Context, in *SendContactRequest, opts ...grpc.CallOption) (*SendContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendContactResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SendContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetMessageStatus(ctx context.Context, in *MessageStatusRequest, opts ...grpc.CallOption) (*MessageStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageStatusResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetMessageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) CreateNewsletter(ctx context.Context, in *CreateNewsletterRequest, opts ...grpc.CallOption) (*CreateNewsletterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewsletterResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_CreateNewsletter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) FollowNewsletter(ctx context.Context, in *FollowNewsletterRequest, opts ...grpc.CallOption) (*FollowNewsletterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowNewsletterResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_FollowNewsletter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetNewsletters(ctx context.Context, in *GetNewslettersRequest, opts ...grpc.CallOption) (*GetNewslettersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewslettersResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetNewsletters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SendNewsletterPoll(ctx context.Context, in *SendNewsletterPollRequest, opts ...grpc.CallOption) (*SendNewsletterPollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNewsletterPollResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SendNewsletterPoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetContacts(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*GetContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContactsResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) CheckNumber(ctx context.Context, in *CheckNumberRequest, opts ...grpc.CallOption) (*CheckNumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNumberResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_CheckNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddContactResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_AddContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetContactDetail(ctx context.Context, in *GetContactDetailRequest, opts ...grpc.CallOption) (*GetContactDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContactDetailResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetContactDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SetProfilePicture(ctx context.Context, in *SetProfilePictureRequest, opts ...grpc.CallOption) (*SetProfilePictureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetProfilePictureResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SetProfilePicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*SetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStatusResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SetDisplayName(ctx context.Context, in *SetDisplayNameRequest, opts ...grpc.CallOption) (*SetDisplayNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDisplayNameResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SetDisplayName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupsResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetGroupMembers(ctx context.Context, in *GetGroupMembersRequest, opts ...grpc.CallOption) (*GetGroupMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMembersResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) AddGroupMembers(ctx context.Context, in *AddGroupMembersRequest, opts ...grpc.CallOption) (*AddGroupMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGroupMembersResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_AddGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) RemoveGroupMembers(ctx context.Context, in *RemoveGroupMembersRequest, opts ...grpc.CallOption) (*RemoveGroupMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveGroupMembersResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_RemoveGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) PromoteGroupMembers(ctx context.Context, in *PromoteGroupMembersRequest, opts ...grpc.CallOption) (*PromoteGroupMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteGroupMembersResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_PromoteGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) DemoteGroupMembers(ctx context.Context, in *DemoteGroupMembersRequest, opts ...grpc.CallOption) (*DemoteGroupMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DemoteGroupMembersResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_DemoteGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveGroupResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SetGroupAdminsOnly(ctx context.Context, in *SetGroupAdminsOnlyRequest, opts ...grpc.CallOption) (*SetGroupAdminsOnlyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGroupAdminsOnlyResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SetGroupAdminsOnly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SetGroupInfoAdminsOnly(ctx context.Context, in *SetGroupInfoAdminsOnlyRequest, opts ...grpc.CallOption) (*SetGroupInfoAdminsOnlyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGroupInfoAdminsOnlyResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SetGroupInfoAdminsOnly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SetGroupAddMembersAdminsOnly(ctx context.Context, in *SetGroupAddMembersAdminsOnlyRequest, opts ...grpc.CallOption) (*SetGroupAddMembersAdminsOnlyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGroupAddMembersAdminsOnlyResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SetGroupAddMembersAdminsOnly_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) ReactToMessage(ctx context.Context, in *ReactToMessageRequest, opts ...grpc.CallOption) (*ReactToMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReactToMessageResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_ReactToMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetMessageReactions(ctx context.Context, in *GetMessageReactionsRequest, opts ...grpc.CallOption) (*GetMessageReactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageReactionsResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetMessageReactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) SendStatus(ctx context.Context, in *SendStatusRequest, opts ...grpc.CallOption) (*SendStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendStatusResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_SendStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) CommentStatus(ctx context.Context, in *CommentStatusRequest, opts ...grpc.CallOption) (*CommentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentStatusResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_CommentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) LikeStatus(ctx context.Context, in *LikeStatusRequest, opts ...grpc.CallOption) (*LikeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeStatusResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_LikeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetStatusViewers(ctx context.Context, in *GetStatusViewersRequest, opts ...grpc.CallOption) (*GetStatusViewersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusViewersResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetStatusViewers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) JoinGroupByLink(ctx context.Context, in *JoinGroupByLinkRequest, opts ...grpc.CallOption) (*JoinGroupByLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGroupByLinkResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_JoinGroupByLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) CloseAllTabs(ctx context.Context, in *CloseAllTabsRequest, opts ...grpc.CallOption) (*CloseAllTabsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseAllTabsResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_CloseAllTabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetAccountStatus(ctx context.Context, in *AccountStatusRequest, opts ...grpc.CallOption) (*AccountStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountStatusResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetAccountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetConnectionState(ctx context.Context, in *ConnectionStateRequest, opts ...grpc.CallOption) (*ConnectionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionStateResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetConnectionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetAccountStats(ctx context.Context, in *GetAccountStatsRequest, opts ...grpc.CallOption) (*GetAccountStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountStatsResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetAccountStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetBridgeStats(ctx context.Context, in *GetBridgeStatsRequest, opts ...grpc.CallOption) (*GetBridgeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBridgeStatsResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetBridgeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) GetWebServerStats(ctx context.Context, in *GetWebServerStatsRequest, opts ...grpc.CallOption) (*WebServerStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebServerStats)
	err := c.cc.Invoke(ctx, WhatsAppBridge_GetWebServerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsAppBridgeClient) BatchGetWebServerStats(ctx context.Context, in *BatchGetWebServerStatsRequest, opts ...grpc.CallOption) (*BatchGetWebServerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetWebServerStatsResponse)
	err := c.cc.Invoke(ctx, WhatsAppBridge_BatchGetWebServerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhatsAppBridgeServer is the server API for WhatsAppBridge service.
// All implementations must embed UnimplementedWhatsAppBridgeServer
// for forward compatibility.
type WhatsAppBridgeServer interface {
	// Connect account (restore from saved session)
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// Disconnect account
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	// Get QR code (streaming, QR refreshes)
	GetQRCode(*QRCodeRequest, grpc.ServerStreamingServer[QRCodeResponse]) error
	// Get link/pairing code (one-time)
	GetLinkCode(context.Context, *LinkCodeRequest) (*LinkCodeResponse, error)
	// Send text message
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// Send media message (image/video/document)
	SendMedia(context.Context, *SendMediaRequest) (*SendMediaResponse, error)
	// Send hyperlink message
	SendLink(context.Context, *SendLinkRequest) (*SendLinkResponse, error)
	// Send contact card (vCard)
	SendContact(context.Context, *SendContactRequest) (*SendContactResponse, error)
	// Get message status
	GetMessageStatus(context.Context, *MessageStatusRequest) (*MessageStatusResponse, error)
	// Create a WhatsApp channel/newsletter
	CreateNewsletter(context.Context, *CreateNewsletterRequest) (*CreateNewsletterResponse, error)
	// Follow a WhatsApp channel/newsletter
	FollowNewsletter(context.Context, *FollowNewsletterRequest) (*FollowNewsletterResponse, error)
	// Get subscribed WhatsApp channels/newsletters
	GetNewsletters(context.Context, *GetNewslettersRequest) (*GetNewslettersResponse, error)
	// Send a poll to a WhatsApp channel/newsletter
	SendNewsletterPoll(context.Context, *SendNewsletterPollRequest) (*SendNewsletterPollResponse, error)
	// Get contacts list
	GetContacts(context.Context, *GetContactsRequest) (*GetContactsResponse, error)
	// Check if numbers are registered on WhatsApp
	CheckNumber(context.Context, *CheckNumberRequest) (*CheckNumberResponse, error)
	// Add contact to address book
	AddContact(context.Context, *AddContactRequest) (*AddContactResponse, error)
	// Get detailed contact information
	GetContactDetail(context.Context, *GetContactDetailRequest) (*GetContactDetailResponse, error)
	// Set profile picture
	SetProfilePicture(context.Context, *SetProfilePictureRequest) (*SetProfilePictureResponse, error)
	// Set profile status text
	SetStatus(context.Context, *SetStatusRequest) (*SetStatusResponse, error)
	// Set display name
	SetDisplayName(context.Context, *SetDisplayNameRequest) (*SetDisplayNameResponse, error)
	// Get groups list
	GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsResponse, error)
	// Get group members
	GetGroupMembers(context.Context, *GetGroupMembersRequest) (*GetGroupMembersResponse, error)
	// Create group
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	// Update group info (name/description)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error)
	// Add members to group
	AddGroupMembers(context.Context, *AddGroupMembersRequest) (*AddGroupMembersResponse, error)
	// Remove members from group
	RemoveGroupMembers(context.Context, *RemoveGroupMembersRequest) (*RemoveGroupMembersResponse, error)
	// Promote members to admin
	PromoteGroupMembers(context.Context, *PromoteGroupMembersRequest) (*PromoteGroupMembersResponse, error)
	// Demote admins to regular members
	DemoteGroupMembers(context.Context, *DemoteGroupMembersRequest) (*DemoteGroupMembersResponse, error)
	// Leave group
	LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error)
	// Delete a message for everyone
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error)
	// Toggle admins-only messaging
	SetGroupAdminsOnly(context.Context, *SetGroupAdminsOnlyRequest) (*SetGroupAdminsOnlyResponse, error)
	// Toggle admins-only group info edit
	SetGroupInfoAdminsOnly(context.Context, *SetGroupInfoAdminsOnlyRequest) (*SetGroupInfoAdminsOnlyResponse, error)
	// Toggle admins-only add members
	SetGroupAddMembersAdminsOnly(context.Context, *SetGroupAddMembersAdminsOnlyRequest) (*SetGroupAddMembersAdminsOnlyResponse, error)
	// React to a message (emoji reaction)
	ReactToMessage(context.Context, *ReactToMessageRequest) (*ReactToMessageResponse, error)
	// Get reactions on a message
	GetMessageReactions(context.Context, *GetMessageReactionsRequest) (*GetMessageReactionsResponse, error)
	// Post a status/story
	SendStatus(context.Context, *SendStatusRequest) (*SendStatusResponse, error)
	// Comment on a status
	CommentStatus(context.Context, *CommentStatusRequest) (*CommentStatusResponse, error)
	// Like/react to a status
	LikeStatus(context.Context, *LikeStatusRequest) (*LikeStatusResponse, error)
	// Get status viewers (who viewed a status post)
	GetStatusViewers(context.Context, *GetStatusViewersRequest) (*GetStatusViewersResponse, error)
	// Join group via invite link
	JoinGroupByLink(context.Context, *JoinGroupByLinkRequest) (*JoinGroupByLinkResponse, error)
	// Close all browser tabs (cleanup)
	CloseAllTabs(context.Context, *CloseAllTabsRequest) (*CloseAllTabsResponse, error)
	// Get account status
	GetAccountStatus(context.Context, *AccountStatusRequest) (*AccountStatusResponse, error)
	// Get connection state
	GetConnectionState(context.Context, *ConnectionStateRequest) (*ConnectionStateResponse, error)
	// Get account online statistics
	GetAccountStats(context.Context, *GetAccountStatsRequest) (*GetAccountStatsResponse, error)
	// Get bridge-wide stats: worker/environment counts and per-worker detail
	GetBridgeStats(context.Context, *GetBridgeStatsRequest) (*GetBridgeStatsResponse, error)
	// Get a single web server's current window usage stats
	GetWebServerStats(context.Context, *GetWebServerStatsRequest) (*WebServerStats, error)
	// Batch get current window usage stats for multiple web servers
	BatchGetWebServerStats(context.Context, *BatchGetWebServerStatsRequest) (*BatchGetWebServerStatsResponse, error)
	mustEmbedUnimplementedWhatsAppBridgeServer()
}

// UnimplementedWhatsAppBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhatsAppBridgeServer struct{}

func (UnimplementedWhatsAppBridgeServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedWhatsAppBridgeServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetQRCode(*QRCodeRequest, grpc.ServerStreamingServer[QRCodeResponse]) error {
	return status.Error(codes.Unimplemented, "method GetQRCode not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetLinkCode(context.Context, *LinkCodeRequest) (*LinkCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinkCode not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SendMedia(context.Context, *SendMediaRequest) (*SendMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMedia not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SendLink(context.Context, *SendLinkRequest) (*SendLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendLink not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SendContact(context.Context, *SendContactRequest) (*SendContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendContact not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetMessageStatus(context.Context, *MessageStatusRequest) (*MessageStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageStatus not implemented")
}
func (UnimplementedWhatsAppBridgeServer) CreateNewsletter(context.Context, *CreateNewsletterRequest) (*CreateNewsletterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNewsletter not implemented")
}
func (UnimplementedWhatsAppBridgeServer) FollowNewsletter(context.Context, *FollowNewsletterRequest) (*FollowNewsletterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowNewsletter not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetNewsletters(context.Context, *GetNewslettersRequest) (*GetNewslettersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewsletters not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SendNewsletterPoll(context.Context, *SendNewsletterPollRequest) (*SendNewsletterPollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNewsletterPoll not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetContacts(context.Context, *GetContactsRequest) (*GetContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContacts not implemented")
}
func (UnimplementedWhatsAppBridgeServer) CheckNumber(context.Context, *CheckNumberRequest) (*CheckNumberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckNumber not implemented")
}
func (UnimplementedWhatsAppBridgeServer) AddContact(context.Context, *AddContactRequest) (*AddContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddContact not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetContactDetail(context.Context, *GetContactDetailRequest) (*GetContactDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContactDetail not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SetProfilePicture(context.Context, *SetProfilePictureRequest) (*SetProfilePictureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProfilePicture not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SetStatus(context.Context, *SetStatusRequest) (*SetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SetDisplayName(context.Context, *SetDisplayNameRequest) (*SetDisplayNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDisplayName not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroups not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetGroupMembers(context.Context, *GetGroupMembersRequest) (*GetGroupMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMembers not implemented")
}
func (UnimplementedWhatsAppBridgeServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedWhatsAppBridgeServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedWhatsAppBridgeServer) AddGroupMembers(context.Context, *AddGroupMembersRequest) (*AddGroupMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGroupMembers not implemented")
}
func (UnimplementedWhatsAppBridgeServer) RemoveGroupMembers(context.Context, *RemoveGroupMembersRequest) (*RemoveGroupMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGroupMembers not implemented")
}
func (UnimplementedWhatsAppBridgeServer) PromoteGroupMembers(context.Context, *PromoteGroupMembersRequest) (*PromoteGroupMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteGroupMembers not implemented")
}
func (UnimplementedWhatsAppBridgeServer) DemoteGroupMembers(context.Context, *DemoteGroupMembersRequest) (*DemoteGroupMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DemoteGroupMembers not implemented")
}
func (UnimplementedWhatsAppBridgeServer) LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedWhatsAppBridgeServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SetGroupAdminsOnly(context.Context, *SetGroupAdminsOnlyRequest) (*SetGroupAdminsOnlyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGroupAdminsOnly not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SetGroupInfoAdminsOnly(context.Context, *SetGroupInfoAdminsOnlyRequest) (*SetGroupInfoAdminsOnlyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGroupInfoAdminsOnly not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SetGroupAddMembersAdminsOnly(context.Context, *SetGroupAddMembersAdminsOnlyRequest) (*SetGroupAddMembersAdminsOnlyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGroupAddMembersAdminsOnly not implemented")
}
func (UnimplementedWhatsAppBridgeServer) ReactToMessage(context.Context, *ReactToMessageRequest) (*ReactToMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReactToMessage not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetMessageReactions(context.Context, *GetMessageReactionsRequest) (*GetMessageReactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageReactions not implemented")
}
func (UnimplementedWhatsAppBridgeServer) SendStatus(context.Context, *SendStatusRequest) (*SendStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendStatus not implemented")
}
func (UnimplementedWhatsAppBridgeServer) CommentStatus(context.Context, *CommentStatusRequest) (*CommentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommentStatus not implemented")
}
func (UnimplementedWhatsAppBridgeServer) LikeStatus(context.Context, *LikeStatusRequest) (*LikeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeStatus not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetStatusViewers(context.Context, *GetStatusViewersRequest) (*GetStatusViewersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatusViewers not implemented")
}
func (UnimplementedWhatsAppBridgeServer) JoinGroupByLink(context.Context, *JoinGroupByLinkRequest) (*JoinGroupByLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGroupByLink not implemented")
}
func (UnimplementedWhatsAppBridgeServer) CloseAllTabs(context.Context, *CloseAllTabsRequest) (*CloseAllTabsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseAllTabs not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetAccountStatus(context.Context, *AccountStatusRequest) (*AccountStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountStatus not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetConnectionState(context.Context, *ConnectionStateRequest) (*ConnectionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectionState not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetAccountStats(context.Context, *GetAccountStatsRequest) (*GetAccountStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountStats not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetBridgeStats(context.Context, *GetBridgeStatsRequest) (*GetBridgeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBridgeStats not implemented")
}
func (UnimplementedWhatsAppBridgeServer) GetWebServerStats(context.Context, *GetWebServerStatsRequest) (*WebServerStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebServerStats not implemented")
}
func (UnimplementedWhatsAppBridgeServer) BatchGetWebServerStats(context.Context, *BatchGetWebServerStatsRequest) (*BatchGetWebServerStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetWebServerStats not implemented")
}
func (UnimplementedWhatsAppBridgeServer) mustEmbedUnimplementedWhatsAppBridgeServer() {}
func (UnimplementedWhatsAppBridgeServer) testEmbeddedByValue()                        {}

// UnsafeWhatsAppBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhatsAppBridgeServer will
// result in compilation errors.
type UnsafeWhatsAppBridgeServer interface {
	mustEmbedUnimplementedWhatsAppBridgeServer()
}

func RegisterWhatsAppBridgeServer(s grpc.ServiceRegistrar, srv WhatsAppBridgeServer) {
	// If the following call panics, it indicates UnimplementedWhatsAppBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhatsAppBridge_ServiceDesc, srv)
}

func _WhatsAppBridge_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetQRCode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QRCodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WhatsAppBridgeServer).GetQRCode(m, &grpc.GenericServerStream[QRCodeRequest, QRCodeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WhatsAppBridge_GetQRCodeServer = grpc.ServerStreamingServer[QRCodeResponse]

func _WhatsAppBridge_GetLinkCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetLinkCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetLinkCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetLinkCode(ctx, req.(*LinkCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SendMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SendMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SendMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SendMedia(ctx, req.(*SendMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SendLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SendLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SendLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SendLink(ctx, req.(*SendLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SendContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SendContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SendContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SendContact(ctx, req.(*SendContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetMessageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetMessageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetMessageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetMessageStatus(ctx, req.(*MessageStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_CreateNewsletter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewsletterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).CreateNewsletter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_CreateNewsletter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).CreateNewsletter(ctx, req.(*CreateNewsletterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_FollowNewsletter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowNewsletterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).FollowNewsletter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_FollowNewsletter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).FollowNewsletter(ctx, req.(*FollowNewsletterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetNewsletters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewslettersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetNewsletters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetNewsletters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetNewsletters(ctx, req.(*GetNewslettersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SendNewsletterPoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNewsletterPollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SendNewsletterPoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SendNewsletterPoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SendNewsletterPoll(ctx, req.(*SendNewsletterPollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetContacts(ctx, req.(*GetContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_CheckNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).CheckNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_CheckNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).CheckNumber(ctx, req.(*CheckNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_AddContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).AddContact(ctx, req.(*AddContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetContactDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetContactDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetContactDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetContactDetail(ctx, req.(*GetContactDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SetProfilePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProfilePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SetProfilePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SetProfilePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SetProfilePicture(ctx, req.(*SetProfilePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SetStatus(ctx, req.(*SetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SetDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDisplayNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SetDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SetDisplayName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SetDisplayName(ctx, req.(*SetDisplayNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetGroups(ctx, req.(*GetGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetGroupMembers(ctx, req.(*GetGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_AddGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).AddGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_AddGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).AddGroupMembers(ctx, req.(*AddGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_RemoveGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).RemoveGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_RemoveGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).RemoveGroupMembers(ctx, req.(*RemoveGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_PromoteGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).PromoteGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_PromoteGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).PromoteGroupMembers(ctx, req.(*PromoteGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_DemoteGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoteGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).DemoteGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_DemoteGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).DemoteGroupMembers(ctx, req.(*DemoteGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).LeaveGroup(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SetGroupAdminsOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupAdminsOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SetGroupAdminsOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SetGroupAdminsOnly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SetGroupAdminsOnly(ctx, req.(*SetGroupAdminsOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SetGroupInfoAdminsOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupInfoAdminsOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SetGroupInfoAdminsOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SetGroupInfoAdminsOnly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SetGroupInfoAdminsOnly(ctx, req.(*SetGroupInfoAdminsOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SetGroupAddMembersAdminsOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupAddMembersAdminsOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SetGroupAddMembersAdminsOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SetGroupAddMembersAdminsOnly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SetGroupAddMembersAdminsOnly(ctx, req.(*SetGroupAddMembersAdminsOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_ReactToMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactToMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).ReactToMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_ReactToMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).ReactToMessage(ctx, req.(*ReactToMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetMessageReactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageReactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetMessageReactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetMessageReactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetMessageReactions(ctx, req.(*GetMessageReactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_SendStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).SendStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_SendStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).SendStatus(ctx, req.(*SendStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_CommentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).CommentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_CommentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).CommentStatus(ctx, req.(*CommentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_LikeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).LikeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_LikeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).LikeStatus(ctx, req.(*LikeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetStatusViewers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusViewersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetStatusViewers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetStatusViewers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetStatusViewers(ctx, req.(*GetStatusViewersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_JoinGroupByLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupByLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).JoinGroupByLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_JoinGroupByLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).JoinGroupByLink(ctx, req.(*JoinGroupByLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_CloseAllTabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAllTabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).CloseAllTabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_CloseAllTabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).CloseAllTabs(ctx, req.(*CloseAllTabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetAccountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetAccountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetAccountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetAccountStatus(ctx, req.(*AccountStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetConnectionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetConnectionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetConnectionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetConnectionState(ctx, req.(*ConnectionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetAccountStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetAccountStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetAccountStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetAccountStats(ctx, req.(*GetAccountStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetBridgeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBridgeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetBridgeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetBridgeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetBridgeStats(ctx, req.(*GetBridgeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_GetWebServerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebServerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).GetWebServerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_GetWebServerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).GetWebServerStats(ctx, req.(*GetWebServerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsAppBridge_BatchGetWebServerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetWebServerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsAppBridgeServer).BatchGetWebServerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsAppBridge_BatchGetWebServerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsAppBridgeServer).BatchGetWebServerStats(ctx, req.(*BatchGetWebServerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhatsAppBridge_ServiceDesc is the grpc.ServiceDesc for WhatsAppBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhatsAppBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.WhatsAppBridge",
	HandlerType: (*WhatsAppBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _WhatsAppBridge_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _WhatsAppBridge_Disconnect_Handler,
		},
		{
			MethodName: "GetLinkCode",
			Handler:    _WhatsAppBridge_GetLinkCode_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _WhatsAppBridge_SendMessage_Handler,
		},
		{
			MethodName: "SendMedia",
			Handler:    _WhatsAppBridge_SendMedia_Handler,
		},
		{
			MethodName: "SendLink",
			Handler:    _WhatsAppBridge_SendLink_Handler,
		},
		{
			MethodName: "SendContact",
			Handler:    _WhatsAppBridge_SendContact_Handler,
		},
		{
			MethodName: "GetMessageStatus",
			Handler:    _WhatsAppBridge_GetMessageStatus_Handler,
		},
		{
			MethodName: "CreateNewsletter",
			Handler:    _WhatsAppBridge_CreateNewsletter_Handler,
		},
		{
			MethodName: "FollowNewsletter",
			Handler:    _WhatsAppBridge_FollowNewsletter_Handler,
		},
		{
			MethodName: "GetNewsletters",
			Handler:    _WhatsAppBridge_GetNewsletters_Handler,
		},
		{
			MethodName: "SendNewsletterPoll",
			Handler:    _WhatsAppBridge_SendNewsletterPoll_Handler,
		},
		{
			MethodName: "GetContacts",
			Handler:    _WhatsAppBridge_GetContacts_Handler,
		},
		{
			MethodName: "CheckNumber",
			Handler:    _WhatsAppBridge_CheckNumber_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _WhatsAppBridge_AddContact_Handler,
		},
		{
			MethodName: "GetContactDetail",
			Handler:    _WhatsAppBridge_GetContactDetail_Handler,
		},
		{
			MethodName: "SetProfilePicture",
			Handler:    _WhatsAppBridge_SetProfilePicture_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _WhatsAppBridge_SetStatus_Handler,
		},
		{
			MethodName: "SetDisplayName",
			Handler:    _WhatsAppBridge_SetDisplayName_Handler,
		},
		{
			MethodName: "GetGroups",
			Handler:    _WhatsAppBridge_GetGroups_Handler,
		},
		{
			MethodName: "GetGroupMembers",
			Handler:    _WhatsAppBridge_GetGroupMembers_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _WhatsAppBridge_CreateGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _WhatsAppBridge_UpdateGroup_Handler,
		},
		{
			MethodName: "AddGroupMembers",
			Handler:    _WhatsAppBridge_AddGroupMembers_Handler,
		},
		{
			MethodName: "RemoveGroupMembers",
			Handler:    _WhatsAppBridge_RemoveGroupMembers_Handler,
		},
		{
			MethodName: "PromoteGroupMembers",
			Handler:    _WhatsAppBridge_PromoteGroupMembers_Handler,
		},
		{
			MethodName: "DemoteGroupMembers",
			Handler:    _WhatsAppBridge_DemoteGroupMembers_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _WhatsAppBridge_LeaveGroup_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _WhatsAppBridge_DeleteMessage_Handler,
		},
		{
			MethodName: "SetGroupAdminsOnly",
			Handler:    _WhatsAppBridge_SetGroupAdminsOnly_Handler,
		},
		{
			MethodName: "SetGroupInfoAdminsOnly",
			Handler:    _WhatsAppBridge_SetGroupInfoAdminsOnly_Handler,
		},
		{
			MethodName: "SetGroupAddMembersAdminsOnly",
			Handler:    _WhatsAppBridge_SetGroupAddMembersAdminsOnly_Handler,
		},
		{
			MethodName: "ReactToMessage",
			Handler:    _WhatsAppBridge_ReactToMessage_Handler,
		},
		{
			MethodName: "GetMessageReactions",
			Handler:    _WhatsAppBridge_GetMessageReactions_Handler,
		},
		{
			MethodName: "SendStatus",
			Handler:    _WhatsAppBridge_SendStatus_Handler,
		},
		{
			MethodName: "CommentStatus",
			Handler:    _WhatsAppBridge_CommentStatus_Handler,
		},
		{
			MethodName: "LikeStatus",
			Handler:    _WhatsAppBridge_LikeStatus_Handler,
		},
		{
			MethodName: "GetStatusViewers",
			Handler:    _WhatsAppBridge_GetStatusViewers_Handler,
		},
		{
			MethodName: "JoinGroupByLink",
			Handler:    _WhatsAppBridge_JoinGroupByLink_Handler,
		},
		{
			MethodName: "CloseAllTabs",
			Handler:    _WhatsAppBridge_CloseAllTabs_Handler,
		},
		{
			MethodName: "GetAccountStatus",
			Handler:    _WhatsAppBridge_GetAccountStatus_Handler,
		},
		{
			MethodName: "GetConnectionState",
			Handler:    _WhatsAppBridge_GetConnectionState_Handler,
		},
		{
			MethodName: "GetAccountStats",
			Handler:    _WhatsAppBridge_GetAccountStats_Handler,
		},
		{
			MethodName: "GetBridgeStats",
			Handler:    _WhatsAppBridge_GetBridgeStats_Handler,
		},
		{
			MethodName: "GetWebServerStats",
			Handler:    _WhatsAppBridge_GetWebServerStats_Handler,
		},
		{
			MethodName: "BatchGetWebServerStats",
			Handler:    _WhatsAppBridge_BatchGetWebServerStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetQRCode",
			Handler:       _WhatsAppBridge_GetQRCode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/bridge.proto",
}
